name: Build and Test Node.js Application

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your repository
      - name: Install Dependencies
        run: npm install  # Install project dependencies
      - name: Run Tests
        run: npm test  # Run your test suite
